service: service

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  layers:
    - arn:aws:lambda:${env:AWS_REGION}:${env:AWS_ACCOUNT_ID}:layer:common:latest

functions:
  hello:
    handler: src/lambdas/hello.handler
    events:
      - http:
          path: /hello
          method: GET

custom:
  esbuild:
    bundle: true
    minify: false
    # These packages will be available within the layers, there's no need
    # to include it within our lambda bundled code.
    exclude:
      - common-layer
      - randomstring

plugins:
  - serverless-esbuild
  - serverless-latest-layer-version
  - serverless-offline
